export const placeholders = [
    'Walk doggo...',
    'You deserve better...',
    'Let it go...',
    'Find new shows to watch...',
    'Listen to favorite podcast...',
    'Look at weather forecast...',
    'Study...',
    'Deliver keynote...',
    'Order treats from Amazon...',
    'Buy flowers for special other...',
    'Call mom...',
    'Vacuum the dog...',
    'Congratulate friend...',
    'Treat myself to my favorite food...',
    'Check in with siblings...',
    'Take out the trash...',
    'Investigate noise behind house...',
    'Reminder to remind myself...',
    'Chop veggies...',
    'Tenderize meat...',
    'Pet the dog...',
    'Get the mail...',
    'Uninstall Netscape...',
    'Pay the bills...',
    'Pay the rent...',
    'Watch Game of Thrones...',
    'Find a scary movie...',
    'Replace lightbulbs...',
    'Buy soap...',
    'Ask myself why...',
    'Turn around...',
    'Wake up...',
    'Buy fruit...',
    'Buy Playstation 5...',
    'Check mortgage rates...',
    'Return the books...',
    'Dye my hair...',
    'Donate to charity...',
    'Cook dinner...',
    'Finish certificate...',
    'Apply for dream job...',
    'Learn how to code...',
    'Discuss politics...',
    'Boop the snoot...',
    'Mow the lawn...',
    'Plant the plant...',
    'Recycle recyclables...',
    'Download Runescape...',
    'Clean the pool...',
    'Buy stonks...',
    'Feed the Sheeb...',
    'Swim with the fishes...',
    'Feed the ducks...',
    'Charge my phone...',
    'Excavate the artifact...',
    'Call the bank...',
    'Row the boat...',
    'Wrap the presents...',
    'Discover Narnia...',
    'Learn Tai Chi...',
    'Explore Atlantis...',
    'Go to Ikea...',
    'Break the sound barrier...',
    'Release the Kraken...',
    'Donate blood...',
    'Learn Farsi...',
    'Buy a birthday cake...',
    'Clean the Earth...',
    'Thwart the foray...',
    'Buy Dogecoin...',
    'Stare into the Void...',
    'Get back on Keto...',
    'Disrupt and industry...'
]
