export const placeholders = [
    'Walk doggo...',
    'You deserve better...',
    'Let it go...',
    'Find new shows to watch...',
    'Listen to favorite podcast...',
    'Look at weather forecast...',
    'Study...',
    'Deliver keynote...',
    'Order treats from Amazon...',
    'Buy flowers for special other...',
    'Call mom...',
    'Congratulate friend...',
    'Treat myself to my favorite food...',
    'Check in with siblings...',
    'Take out the trash...',
    'Investigate noise behind house...',
    'Reminder to remind myself...',
    'Chop veggies...',
    'Tenderize meat...',
    'Pet the dog...',
    'Get the mail...',
    'Uninstall Netscape...',
    'Pay the bills...',
    'Pay the rent...',
    'Watch Game of Thrones',
    'Find a scary movie...',
    'Replace lightbulbs...',
    'Buy soap...',
    'Ask myself why...',
    'Turn around...',
    'Wake up...',
    'Buy fruit...',
    'Buy Playstation 5...',
    'Check mortgage rates...',
    'Return the books...',
    'Dye my hair...',
    'Donate to charity...'
]